### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by tmastersmart** [wb4bxo/UV-5R-COS#1]
I don't need a board where's the schematic?

**Comment by wb4bxo** [comment]
This is the KiCad project. If you open it with KiCad you'll see the schematic. Alternately you can look at the link below and see pictures and pdf files. This board is ALMOST the same as the BJT version you'll see there.
https://www.dropbox.com/scl/fo/ijx6qdvklskfgv19kaams/ABsIuqHEEbqoYNm4X1Uc1b4?rlkey=346zcdpkfad4y5mk4jwmj165i&dl=0
